export { Dashboard } from "./Dashboard"
export type { DashboardComponent, DashboardProps } from "./Dashboard"
export { About } from "./About"
export type { AboutComponent, AboutProps } from "./About"
export { Portfolio } from "./Portfolio"
export type { PortfolioComponent, PortfolioProps } from "./Portfolio"
